<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Compliance</name>
   <tag></tag>
   <elementGuidId>413f2ffa-ec05-41c7-879f-50a5bb9aa87e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='l2-101_3-ListItem1']/div/a/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#l2-101_3-ListItem1 > div > a > span.OSFillParent</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>970fff21-c51d-4051-83d7-c61613c2f2b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>OSFillParent</value>
      <webElementGuid>13873566-5b1d-42f6-81ec-8a4460375dfc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Compliance</value>
      <webElementGuid>bcb9fcda-0068-451a-b7a2-719a30efcc67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;l2-101_3-ListItem1&quot;)/div[1]/a[1]/span[@class=&quot;OSFillParent&quot;]</value>
      <webElementGuid>7a8c6423-7b76-4047-80a8-dc2a394d649d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='l2-101_3-ListItem1']/div/a/span</value>
      <webElementGuid>e3dc7a91-b262-414b-839b-68f46712b379</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Book Keeper'])[1]/following::span[1]</value>
      <webElementGuid>4897f72e-f09c-4d27-8fbf-645d8c2cdc7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Area Manager'])[1]/following::span[2]</value>
      <webElementGuid>a0cebd43-d01d-4c60-ab5f-30f99ece78ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Finance'])[1]/preceding::span[1]</value>
      <webElementGuid>5795eab2-1d98-4eaa-9e7a-87aaf33c130b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Risk'])[1]/preceding::span[2]</value>
      <webElementGuid>0b502107-16d8-4812-9b62-2b4811781daf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Compliance']/parent::*</value>
      <webElementGuid>5f32643f-2c8c-4049-80be-9196fea6acdc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/a/span</value>
      <webElementGuid>906be10a-88dd-4bd4-8a6a-8dbb67d1be6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Compliance' or . = 'Compliance')]</value>
      <webElementGuid>05c646e1-d963-43ee-bbab-edada8a8f765</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
